### ISSUE TITLE
update yarn from 1.22.22

### ISSUE THREAD

**Issue by entin-hun** [szekelyisz/ffd-tm-editor#2]
regardless “`corepack prepare yarn@4.3.1 --activate`”, the error for any yarn is still: 

> This project's package.json defines "packageManager": "yarn@4.3.1". However the current global version of Yarn is 1.22.22.

> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
> Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.

**Comment by szekelyisz** [comment]
You're still using yarn 1.22.22. Try `yarn set version 4.3.1` then make sure `yarn --version` reports 4.3.1.
